---
- include_vars: production_email.yml
  when: server_env == "production"

- name: Install mail utils
  apt: name=mailutils state=present

- name: Set Postfix option hostname
  debconf: name=postifx question="postfix/mailname" value="{{ server_name }}" vtype="string"

- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"

- name: install postfix
  apt: name=postfix state=present

- name: set postfix relay host
  lineinfile: dest=/etc/postfix/main.cf regexp=^relayhost line='relayhost = {{smtp_server_relayhost}}'

#### turns out I had to fill this in with the local domain in order to get qa email to foward... so keep an eye on this
- name: set postfix my destination
  lineinfile: dest=/etc/postfix/main.cf regexp=^mydestination line='mydestination = '

- name: set postfix auth enable yes
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtp_sasl_auth_enable line='smtp_sasl_auth_enable = yes' create=yes

- name: set postfix use tls to yes
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtp_use_tls line='smtp_use_tls = yes' create=yes

- name: set postfix mechanism filter to plain
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtp_sasl_mechanism_filter line='smtp_sasl_machanism_filter = plain' create=yes

- name: set postfix anonymous not allowed
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtp_sasl_security_options line='smtp_sasl_security_options = noanonymous' create=yes

- name: set postfix ca location
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtp_tls_CAfile line='smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt' create=yes

- name: set postfix password maps
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtp_sasl_password_maps line='smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd' create=yes

- name: Copy across password file
  template:
    src=sasl_passwd.j2
    dest=/etc/postfix/sasl_passwd

- name: Postmap to a db file
  command: postmap /etc/postfix/sasl_passwd

- name: add forward users to alias for root
  lineinfile: "dest=/etc/aliases line='root: {{ notification_email }}' create=yes"

- name: add forward users to alias for ayron
  lineinfile: "dest=/etc/aliases line='vagrant: {{ notification_email }}' create=yes"

- name: alert new aliases
  command: newaliases

  notify:
    - restart postfix
